s/Tom/John/g
s/Bill/John/g
s/Mary/Paris/g
s/Lisa/Paris/g
s/Sue/Paris/g
s/body/thing/g
s/who\(.*\)?/what\1?/g
s/who/that/g
s/loves/finds/g
s/loved/found/g
s/love/find/g
s/admire/hate/g
s/helped/bitten/g
s/help/bite/g
s/golfer/cat/g
s/an officer/a bird/g
s/officer/bird/g
s/traveler/horse/g
s/picture/tail/g
s/woman/worm/g
s/women/worms/g
s/man/dog/g
s/men/dogs/g
s/presents/policemen/g
s/present/policeman/g
s/aquarium/airplane/g
s/inspect/understand/g
s/person/book/g
s/understands/pushes/g
s/understand/push/g
s/buys/fears/g
s/buy/fear/g
s/bought/feared/g
