s/Tom/John/g
s/Bill/John/g
s/Mary/Paris/g
s/Lisa/Paris/g
s/Sue/Paris/g
s/body/thing/g
s/who\(.*\)?/what\1?/g
s/who/that/g
s/loves/holds/g
s/loved/held/g
s/love/hold/g
s/admire/forget/g
s/help/count/g
s/golfer/grammar/g
s/officer/apple/g
s/traveler/house/g
s/picture/bank/g
s/present/garden/g
s/aquarium/airplane/g
s/inspect/understand/g
s/woman/bread/g
s/women/breads/g
s/man/chair/g
s/men/chairs/g
s/person/book/g
